Add section "reviews" for mobile
izachok/icecream-project pull request #14
Opened 2021-06-05 13:28 UTC by Taras-Kolomiiets

Add mvp section "reviews" for mobile )

2021-06-05 14:31 UTC, Mandzirokha commented on src/partials/customer-reviews.html
> +      width="85px"
ширину картинки вказуємо без px

2021-06-05 19:25 UTC, izachok requested changes
Visually looks great

2021-06-05 19:25 UTC, izachok commented on src/sass/layouts/_customer-reviews.scss
> +  margin-top: 80px;
change to padding

2021-06-05 19:25 UTC, izachok commented on src/sass/layouts/_customer-reviews.scss
> +  background-color: var(--slider-backg-color);
background-color was inherited from parent. delete it

2021-06-05 19:25 UTC, izachok commented on src/sass/layouts/_customer-reviews.scss
> +  height: 248px;
I think text should also be responsive in range 320-480. Only paddings should regulate it's position

2021-06-05 19:25 UTC, izachok commented on src/partials/customer-reviews.html
> +          <use href="./images/icons.svg#icon-brackets"></use>
it should be pseudoelement by requirements

2021-06-05 19:25 UTC, izachok commented on src/sass/layouts/_customer-reviews.scss
> +  font-family: 'DMSans-Medium';
is it possible change it to variable?

2021-06-05 19:25 UTC, izachok commented on src/partials/customer-reviews.html
> +        <use href="./images/icons.svg#icon-circle"></use>
it should be pseudoelement by requirements

2021-06-05 19:25 UTC, izachok commented on src/sass/layouts/_customer-reviews.scss
> +  margin-top: 80px;
should you add bottom padding as well?

2021-06-06 15:29 UTC, izachok approved these changes

2021-06-06 15:30 UTC, merged